"""
State module for RAG application.
Defines the data structure that flows through the LangGraph.
"""

from typing import List, TypedDict
from langchain_core.messages import BaseMessage


class RAGState(TypedDict):
    """
    State object that holds all data flowing through our LangGraph.
    
    Attributes:
        question (str): The user's current question
        chat_history (List[BaseMessage]): List of previous messages
        context (List): Retrieved documents
        answer (str): The final answer generated by the LLM
        should_retrieve (bool): Flag to decide if we need to retrieve documents
    """
    question: str
    chat_history: List[BaseMessage]
    context: List
    answer: str
    should_retrieve: bool

"""
Directory structure:
langgrap/
├── config.py         # Models & vector store setup
├── state.py          # State definition
├── nodes.py          # Graph nodes
├── graph.py          # Graph building
└── main.py           # Main entry point
"""
